// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: transactions.capnp

package com.wavesplatform.transactions.capnp;

public final class Transactions {
  public static class Recipient {
    public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)1,(short)1);
    public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
      public Factory() {
      }
      public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
        return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
      }
      public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
        return new Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final org.capnproto.StructSize structSize() {
        return Recipient.STRUCT_SIZE;
      }
      public final Reader asReader(Builder builder) {
        return builder.asReader();
      }
    }
    public static final Factory factory = new Factory();
    public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
      new org.capnproto.StructList.Factory<Builder, Reader>(factory);
    public static final class Builder extends org.capnproto.StructBuilder {
      Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
        super(segment, data, pointers, dataSize, pointerCount);
      }
      public Which which() {
        switch(_getShortField(2)) {
          case 0 : return Which.ADDRESS;
          case 1 : return Which.ALIAS;
          default: return Which._NOT_IN_SCHEMA;
        }
      }
      public final Reader asReader() {
        return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
      }
      public final int getChainId() {
        return _getIntField(0);
      }
      public final void setChainId(int value) {
        _setIntField(0, value);
      }

      public final boolean isAddress() {
        return which() == Recipient.Which.ADDRESS;
      }
      public final boolean hasAddress() {
        if (which() != Recipient.Which.ADDRESS) return false;
        return !_pointerFieldIsNull(0);
      }
      public final org.capnproto.Data.Builder getAddress() {
        return _getPointerField(org.capnproto.Data.factory, 0, null, 0, 0);
      }
      public final void setAddress(org.capnproto.Data.Reader value) {
        _setShortField(2, (short)Recipient.Which.ADDRESS.ordinal());
        _setPointerField(org.capnproto.Data.factory, 0, value);
      }
      public final void setAddress(byte [] value) {
        _setShortField(2, (short)Recipient.Which.ADDRESS.ordinal());
        _setPointerField(org.capnproto.Data.factory, 0, new org.capnproto.Data.Reader(value));
      }
      public final org.capnproto.Data.Builder initAddress(int size) {
        _setShortField(2, (short)Recipient.Which.ADDRESS.ordinal());
        return _initPointerField(org.capnproto.Data.factory, 0, size);
      }
      public final boolean isAlias() {
        return which() == Recipient.Which.ALIAS;
      }
      public final boolean hasAlias() {
        if (which() != Recipient.Which.ALIAS) return false;
        return !_pointerFieldIsNull(0);
      }
      public final org.capnproto.Text.Builder getAlias() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }
      public final void setAlias(org.capnproto.Text.Reader value) {
        _setShortField(2, (short)Recipient.Which.ALIAS.ordinal());
        _setPointerField(org.capnproto.Text.factory, 0, value);
      }
      public final void setAlias(String value) {
        _setShortField(2, (short)Recipient.Which.ALIAS.ordinal());
        _setPointerField(org.capnproto.Text.factory, 0, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initAlias(int size) {
        _setShortField(2, (short)Recipient.Which.ALIAS.ordinal());
        return _initPointerField(org.capnproto.Text.factory, 0, size);
      }
    }

    public static final class Reader extends org.capnproto.StructReader {
      Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
        super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public Which which() {
        switch(_getShortField(2)) {
          case 0 : return Which.ADDRESS;
          case 1 : return Which.ALIAS;
          default: return Which._NOT_IN_SCHEMA;
        }
      }
      public final int getChainId() {
        return _getIntField(0);
      }

      public final boolean isAddress() {
        return which() == Recipient.Which.ADDRESS;
      }
      public boolean hasAddress() {
        if (which() != Recipient.Which.ADDRESS) return false;
        return !_pointerFieldIsNull(0);
      }
      public org.capnproto.Data.Reader getAddress() {
        return _getPointerField(org.capnproto.Data.factory, 0, null, 0, 0);
      }

      public final boolean isAlias() {
        return which() == Recipient.Which.ALIAS;
      }
      public boolean hasAlias() {
        if (which() != Recipient.Which.ALIAS) return false;
        return !_pointerFieldIsNull(0);
      }
      public org.capnproto.Text.Reader getAlias() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }

    }

    public enum Which {
      ADDRESS,
      ALIAS,
      _NOT_IN_SCHEMA,
    }
  }


  public static class Transaction {
    public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)4,(short)3);
    public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
      public Factory() {
      }
      public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
        return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
      }
      public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
        return new Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final org.capnproto.StructSize structSize() {
        return Transaction.STRUCT_SIZE;
      }
      public final Reader asReader(Builder builder) {
        return builder.asReader();
      }
    }
    public static final Factory factory = new Factory();
    public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
      new org.capnproto.StructList.Factory<Builder, Reader>(factory);
    public static final class Builder extends org.capnproto.StructBuilder {
      Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
        super(segment, data, pointers, dataSize, pointerCount);
      }
      public final Reader asReader() {
        return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
      }
      public final boolean hasSender() {
        return !_pointerFieldIsNull(0);
      }
      public final org.capnproto.Data.Builder getSender() {
        return _getPointerField(org.capnproto.Data.factory, 0, null, 0, 0);
      }
      public final void setSender(org.capnproto.Data.Reader value) {
        _setPointerField(org.capnproto.Data.factory, 0, value);
      }
      public final void setSender(byte [] value) {
        _setPointerField(org.capnproto.Data.factory, 0, new org.capnproto.Data.Reader(value));
      }
      public final org.capnproto.Data.Builder initSender(int size) {
        return _initPointerField(org.capnproto.Data.factory, 0, size);
      }
      public final byte getChainId() {
        return _getByteField(0);
      }
      public final void setChainId(byte value) {
        _setByteField(0, value);
      }

      public final Fee.Builder getFee() {
        return new Transaction.Fee.Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final Fee.Builder initFee() {
        _setLongField(1,0L);
        _clearPointerField(1);
  return new Transaction.Fee.Builder(segment, data, pointers, dataSize, pointerCount);
      }

      public final long getTimestamp() {
        return _getLongField(2);
      }
      public final void setTimestamp(long value) {
        _setLongField(2, value);
      }

      public final byte getVersion() {
        return _getByteField(1);
      }
      public final void setVersion(byte value) {
        _setByteField(1, value);
      }

      public final Data.Builder getData() {
        return new Transaction.Data.Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final Data.Builder initData() {
        _setShortField(1,(short)0);
        _setLongField(3,0L);
        _clearPointerField(2);
  return new Transaction.Data.Builder(segment, data, pointers, dataSize, pointerCount);
      }

    }

    public static final class Reader extends org.capnproto.StructReader {
      Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
        super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public boolean hasSender() {
        return !_pointerFieldIsNull(0);
      }
      public org.capnproto.Data.Reader getSender() {
        return _getPointerField(org.capnproto.Data.factory, 0, null, 0, 0);
      }

      public final byte getChainId() {
        return _getByteField(0);
      }

      public Fee.Reader getFee() {
        return new Transaction.Fee.Reader(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public final long getTimestamp() {
        return _getLongField(2);
      }

      public final byte getVersion() {
        return _getByteField(1);
      }

      public Data.Reader getData() {
        return new Transaction.Data.Reader(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

    }

    public static class Fee {
      public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)4,(short)3);
      public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
        public Factory() {
        }
        public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
          return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
        }
        public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
          return new Builder(segment, data, pointers, dataSize, pointerCount);
        }
        public final org.capnproto.StructSize structSize() {
          return Transaction.Fee.STRUCT_SIZE;
        }
        public final Reader asReader(Builder builder) {
          return builder.asReader();
        }
      }
      public static final Factory factory = new Factory();
      public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
        new org.capnproto.StructList.Factory<Builder, Reader>(factory);
      public static final class Builder extends org.capnproto.StructBuilder {
        Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
          super(segment, data, pointers, dataSize, pointerCount);
        }
        public final Reader asReader() {
          return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
        }
        public final long getAmount() {
          return _getLongField(1);
        }
        public final void setAmount(long value) {
          _setLongField(1, value);
        }

        public final boolean hasAssetId() {
          return !_pointerFieldIsNull(1);
        }
        public final org.capnproto.Data.Builder getAssetId() {
          return _getPointerField(org.capnproto.Data.factory, 1, null, 0, 0);
        }
        public final void setAssetId(org.capnproto.Data.Reader value) {
          _setPointerField(org.capnproto.Data.factory, 1, value);
        }
        public final void setAssetId(byte [] value) {
          _setPointerField(org.capnproto.Data.factory, 1, new org.capnproto.Data.Reader(value));
        }
        public final org.capnproto.Data.Builder initAssetId(int size) {
          return _initPointerField(org.capnproto.Data.factory, 1, size);
        }
      }

      public static final class Reader extends org.capnproto.StructReader {
        Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
          super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
        }

        public final long getAmount() {
          return _getLongField(1);
        }

        public boolean hasAssetId() {
          return !_pointerFieldIsNull(1);
        }
        public org.capnproto.Data.Reader getAssetId() {
          return _getPointerField(org.capnproto.Data.factory, 1, null, 0, 0);
        }

      }

    }


    public static class Data {
      public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)4,(short)3);
      public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
        public Factory() {
        }
        public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
          return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
        }
        public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
          return new Builder(segment, data, pointers, dataSize, pointerCount);
        }
        public final org.capnproto.StructSize structSize() {
          return Transaction.Data.STRUCT_SIZE;
        }
        public final Reader asReader(Builder builder) {
          return builder.asReader();
        }
      }
      public static final Factory factory = new Factory();
      public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
        new org.capnproto.StructList.Factory<Builder, Reader>(factory);
      public static final class Builder extends org.capnproto.StructBuilder {
        Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
          super(segment, data, pointers, dataSize, pointerCount);
        }
        public Which which() {
          switch(_getShortField(1)) {
            case 0 : return Which.GENESIS;
            case 1 : return Which.PAYMENT;
            default: return Which._NOT_IN_SCHEMA;
          }
        }
        public final Reader asReader() {
          return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
        }
        public final boolean isGenesis() {
          return which() == Transaction.Data.Which.GENESIS;
        }
        public final Genesis.Builder getGenesis() {
          return new Transaction.Data.Genesis.Builder(segment, data, pointers, dataSize, pointerCount);
        }
        public final Genesis.Builder initGenesis() {
          _setShortField(1, (short)Transaction.Data.Which.GENESIS.ordinal());
          _setLongField(3,0L);
          _clearPointerField(2);
  return new Transaction.Data.Genesis.Builder(segment, data, pointers, dataSize, pointerCount);
        }

        public final boolean isPayment() {
          return which() == Transaction.Data.Which.PAYMENT;
        }
        public final Payment.Builder getPayment() {
          return new Transaction.Data.Payment.Builder(segment, data, pointers, dataSize, pointerCount);
        }
        public final Payment.Builder initPayment() {
          _setShortField(1, (short)Transaction.Data.Which.PAYMENT.ordinal());
          _setLongField(3,0L);
          _clearPointerField(2);
  return new Transaction.Data.Payment.Builder(segment, data, pointers, dataSize, pointerCount);
        }

      }

      public static final class Reader extends org.capnproto.StructReader {
        Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
          super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
        }

        public Which which() {
          switch(_getShortField(1)) {
            case 0 : return Which.GENESIS;
            case 1 : return Which.PAYMENT;
            default: return Which._NOT_IN_SCHEMA;
          }
        }
        public final boolean isGenesis() {
          return which() == Transaction.Data.Which.GENESIS;
        }
        public Genesis.Reader getGenesis() {
          return new Transaction.Data.Genesis.Reader(segment, data, pointers, dataSize, pointerCount, nestingLimit);
        }

        public final boolean isPayment() {
          return which() == Transaction.Data.Which.PAYMENT;
        }
        public Payment.Reader getPayment() {
          return new Transaction.Data.Payment.Reader(segment, data, pointers, dataSize, pointerCount, nestingLimit);
        }

      }

      public enum Which {
        GENESIS,
        PAYMENT,
        _NOT_IN_SCHEMA,
      }
      public static class Genesis {
        public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)4,(short)3);
        public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
          public Factory() {
          }
          public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
            return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
          }
          public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
            return new Builder(segment, data, pointers, dataSize, pointerCount);
          }
          public final org.capnproto.StructSize structSize() {
            return Transaction.Data.Genesis.STRUCT_SIZE;
          }
          public final Reader asReader(Builder builder) {
            return builder.asReader();
          }
        }
        public static final Factory factory = new Factory();
        public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
          new org.capnproto.StructList.Factory<Builder, Reader>(factory);
        public static final class Builder extends org.capnproto.StructBuilder {
          Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
            super(segment, data, pointers, dataSize, pointerCount);
          }
          public final Reader asReader() {
            return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
          }
          public final com.wavesplatform.transactions.capnp.Transactions.Recipient.Builder getRecipient() {
            return _getPointerField(com.wavesplatform.transactions.capnp.Transactions.Recipient.factory, 2, null, 0);
          }
          public final void setRecipient(com.wavesplatform.transactions.capnp.Transactions.Recipient.Reader value) {
            _setPointerField(com.wavesplatform.transactions.capnp.Transactions.Recipient.factory,2, value);
          }
          public final com.wavesplatform.transactions.capnp.Transactions.Recipient.Builder initRecipient() {
            return _initPointerField(com.wavesplatform.transactions.capnp.Transactions.Recipient.factory,2, 0);
          }
          public final long getAmount() {
            return _getLongField(3);
          }
          public final void setAmount(long value) {
            _setLongField(3, value);
          }

        }

        public static final class Reader extends org.capnproto.StructReader {
          Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
            super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
          }

          public boolean hasRecipient() {
            return !_pointerFieldIsNull(2);
          }
          public com.wavesplatform.transactions.capnp.Transactions.Recipient.Reader getRecipient() {
            return _getPointerField(com.wavesplatform.transactions.capnp.Transactions.Recipient.factory,2,null, 0);
          }

          public final long getAmount() {
            return _getLongField(3);
          }

        }

      }


      public static class Payment {
        public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)4,(short)3);
        public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
          public Factory() {
          }
          public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
            return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
          }
          public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
            return new Builder(segment, data, pointers, dataSize, pointerCount);
          }
          public final org.capnproto.StructSize structSize() {
            return Transaction.Data.Payment.STRUCT_SIZE;
          }
          public final Reader asReader(Builder builder) {
            return builder.asReader();
          }
        }
        public static final Factory factory = new Factory();
        public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
          new org.capnproto.StructList.Factory<Builder, Reader>(factory);
        public static final class Builder extends org.capnproto.StructBuilder {
          Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
            super(segment, data, pointers, dataSize, pointerCount);
          }
          public final Reader asReader() {
            return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
          }
          public final com.wavesplatform.transactions.capnp.Transactions.Recipient.Builder getRecipient() {
            return _getPointerField(com.wavesplatform.transactions.capnp.Transactions.Recipient.factory, 2, null, 0);
          }
          public final void setRecipient(com.wavesplatform.transactions.capnp.Transactions.Recipient.Reader value) {
            _setPointerField(com.wavesplatform.transactions.capnp.Transactions.Recipient.factory,2, value);
          }
          public final com.wavesplatform.transactions.capnp.Transactions.Recipient.Builder initRecipient() {
            return _initPointerField(com.wavesplatform.transactions.capnp.Transactions.Recipient.factory,2, 0);
          }
          public final long getAmount() {
            return _getLongField(3);
          }
          public final void setAmount(long value) {
            _setLongField(3, value);
          }

        }

        public static final class Reader extends org.capnproto.StructReader {
          Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
            super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
          }

          public boolean hasRecipient() {
            return !_pointerFieldIsNull(2);
          }
          public com.wavesplatform.transactions.capnp.Transactions.Recipient.Reader getRecipient() {
            return _getPointerField(com.wavesplatform.transactions.capnp.Transactions.Recipient.factory,2,null, 0);
          }

          public final long getAmount() {
            return _getLongField(3);
          }

        }

      }


    }


  }



public static final class Schemas {
public static final org.capnproto.SegmentReader b_c731f848a15b3419 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u0019\u0034\u005b\u00a1\u0048\u00f8\u0031\u00c7" +
   "\u0013\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u00e5\u003e\u00c6\u0032\u00b8\u0092\u0083\u00bd" +
   "\u0001\u0000\u0007\u0000\u0000\u0000\u0002\u0000" +
   "\u0002\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00ea\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u00af\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0074\u0072\u0061\u006e\u0073\u0061\u0063\u0074" +
   "\u0069\u006f\u006e\u0073\u002e\u0063\u0061\u0070" +
   "\u006e\u0070\u003a\u0052\u0065\u0063\u0069\u0070" +
   "\u0069\u0065\u006e\u0074\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u000c\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0045\u0000\u0000\u0000\u0042\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0040\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u004c\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0001\u0000\u00ff\u00ff\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0049\u0000\u0000\u0000\u0042\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0044\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0050\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0002\u0000\u00fe\u00ff\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u004d\u0000\u0000\u0000\u0032\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0048\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0054\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0063\u0068\u0061\u0069\u006e\u0049\u0064\u0000" +
   "\u0008\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0008\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0064\u0064\u0072\u0065\u0073\u0073\u0000" +
   "\r\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\r\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u006c\u0069\u0061\u0073\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_b40c8a0208174d73 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u0073\u004d\u0017\u0008\u0002\u008a\u000c\u00b4" +
   "\u0013\u0000\u0000\u0000\u0001\u0000\u0004\u0000" +
   "\u00e5\u003e\u00c6\u0032\u00b8\u0092\u0083\u00bd" +
   "\u0003\u0000\u0007\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00fa\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u0057\u0001\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0074\u0072\u0061\u006e\u0073\u0061\u0063\u0074" +
   "\u0069\u006f\u006e\u0073\u002e\u0063\u0061\u0070" +
   "\u006e\u0070\u003a\u0054\u0072\u0061\u006e\u0073" +
   "\u0061\u0063\u0074\u0069\u006f\u006e\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u0018\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0099\u0000\u0000\u0000\u003a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0094\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00a0\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u009d\u0000\u0000\u0000\u0042\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0098\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00a4\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0002\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0060\u0043\u0035\u00d5\u00f6\u0014\u002d\u00a2" +
   "\u00a1\u0000\u0000\u0000\"\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0003\u0000\u0000\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0004\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0089\u0000\u0000\u0000\u0052\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0088\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0094\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0004\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0005\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0091\u0000\u0000\u0000\u0042\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u008c\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0098\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0005\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0092\u005a\u0077\u0063\u00b8\"\u0027\u00fd" +
   "\u0095\u0000\u0000\u0000\u002a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0073\u0065\u006e\u0064\u0065\u0072\u0000\u0000" +
   "\r\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\r\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0063\u0068\u0061\u0069\u006e\u0049\u0064\u0000" +
   "\u0006\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0006\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0066\u0065\u0065\u0000\u0000\u0000\u0000\u0000" +
   "\u0074\u0069\u006d\u0065\u0073\u0074\u0061\u006d" +
   "\u0070\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0005\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0005\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0076\u0065\u0072\u0073\u0069\u006f\u006e\u0000" +
   "\u0006\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0006\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0064\u0061\u0074\u0061\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_a22d14f6d5354360 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u0060\u0043\u0035\u00d5\u00f6\u0014\u002d\u00a2" +
   "\u001f\u0000\u0000\u0000\u0001\u0000\u0004\u0000" +
   "\u0073\u004d\u0017\u0008\u0002\u008a\u000c\u00b4" +
   "\u0003\u0000\u0007\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u001a\u0001\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u0077\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0074\u0072\u0061\u006e\u0073\u0061\u0063\u0074" +
   "\u0069\u006f\u006e\u0073\u002e\u0063\u0061\u0070" +
   "\u006e\u0070\u003a\u0054\u0072\u0061\u006e\u0073" +
   "\u0061\u0063\u0074\u0069\u006f\u006e\u002e\u0066" +
   "\u0065\u0065\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0008\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0029\u0000\u0000\u0000\u003a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0024\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0030\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0001\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0003\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u002d\u0000\u0000\u0000\u0042\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0028\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0034\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0061\u006d\u006f\u0075\u006e\u0074\u0000\u0000" +
   "\u0005\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0005\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0073\u0073\u0065\u0074\u0049\u0064\u0000" +
   "\r\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\r\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_fd2722b863775a92 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u0092\u005a\u0077\u0063\u00b8\"\u0027\u00fd" +
   "\u001f\u0000\u0000\u0000\u0001\u0000\u0004\u0000" +
   "\u0073\u004d\u0017\u0008\u0002\u008a\u000c\u00b4" +
   "\u0003\u0000\u0007\u0000\u0001\u0000\u0002\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\"\u0001\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u0077\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0074\u0072\u0061\u006e\u0073\u0061\u0063\u0074" +
   "\u0069\u006f\u006e\u0073\u002e\u0063\u0061\u0070" +
   "\u006e\u0070\u003a\u0054\u0072\u0061\u006e\u0073" +
   "\u0061\u0063\u0074\u0069\u006f\u006e\u002e\u0064" +
   "\u0061\u0074\u0061\u0000\u0000\u0000\u0000\u0000" +
   "\u0008\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u00ff\u00ff\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00a3\u00a1\u00f6\u003a\u006d\u0074\u00a7\u00fe" +
   "\u0029\u0000\u0000\u0000\u0042\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u00fe\u00ff\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00c7\u00ae\u00d1\u001e\u00d9\u00af\u0031\u00d2" +
   "\u0011\u0000\u0000\u0000\u0042\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0067\u0065\u006e\u0065\u0073\u0069\u0073\u0000" +
   "\u0070\u0061\u0079\u006d\u0065\u006e\u0074\u0000" + "");
public static final org.capnproto.SegmentReader b_fea7746d3af6a1a3 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u00a3\u00a1\u00f6\u003a\u006d\u0074\u00a7\u00fe" +
   "\u0024\u0000\u0000\u0000\u0001\u0000\u0004\u0000" +
   "\u0092\u005a\u0077\u0063\u00b8\"\u0027\u00fd" +
   "\u0003\u0000\u0007\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u0062\u0001\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0077\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0074\u0072\u0061\u006e\u0073\u0061\u0063\u0074" +
   "\u0069\u006f\u006e\u0073\u002e\u0063\u0061\u0070" +
   "\u006e\u0070\u003a\u0054\u0072\u0061\u006e\u0073" +
   "\u0061\u0063\u0074\u0069\u006f\u006e\u002e\u0064" +
   "\u0061\u0074\u0061\u002e\u0067\u0065\u006e\u0065" +
   "\u0073\u0069\u0073\u0000\u0000\u0000\u0000\u0000" +
   "\u0008\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0006\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0029\u0000\u0000\u0000\u0052\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0028\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0034\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0001\u0000\u0000\u0000\u0003\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0031\u0000\u0000\u0000\u003a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u002c\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0038\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0072\u0065\u0063\u0069\u0070\u0069\u0065\u006e" +
   "\u0074\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0019\u0034\u005b\u00a1\u0048\u00f8\u0031\u00c7" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u006d\u006f\u0075\u006e\u0074\u0000\u0000" +
   "\u0005\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0005\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_d231afd91ed1aec7 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u00c7\u00ae\u00d1\u001e\u00d9\u00af\u0031\u00d2" +
   "\u0024\u0000\u0000\u0000\u0001\u0000\u0004\u0000" +
   "\u0092\u005a\u0077\u0063\u00b8\"\u0027\u00fd" +
   "\u0003\u0000\u0007\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u0062\u0001\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0077\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0074\u0072\u0061\u006e\u0073\u0061\u0063\u0074" +
   "\u0069\u006f\u006e\u0073\u002e\u0063\u0061\u0070" +
   "\u006e\u0070\u003a\u0054\u0072\u0061\u006e\u0073" +
   "\u0061\u0063\u0074\u0069\u006f\u006e\u002e\u0064" +
   "\u0061\u0074\u0061\u002e\u0070\u0061\u0079\u006d" +
   "\u0065\u006e\u0074\u0000\u0000\u0000\u0000\u0000" +
   "\u0008\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0008\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0029\u0000\u0000\u0000\u0052\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0028\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0034\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0001\u0000\u0000\u0000\u0003\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0009\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0031\u0000\u0000\u0000\u003a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u002c\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0038\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0072\u0065\u0063\u0069\u0070\u0069\u0065\u006e" +
   "\u0074\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0019\u0034\u005b\u00a1\u0048\u00f8\u0031\u00c7" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u006d\u006f\u0075\u006e\u0074\u0000\u0000" +
   "\u0005\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0005\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
}
}

