{
 "title": "RIDE runner",
 "tags": [
  "kamon",
  "prometheus",
  "ride"
 ],
 "time": { "from": "2023-02-16T04:44:19.529Z", "to": "2023-02-16T07:58:29.780Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "app_filter", "label": "App filter", "query": ".*" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(up{job=~\"$app_filter\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "client_operation",
    "query": {
     "query": "label_values(span_processing_time_seconds_count{job=~\"$job\", span_kind=\"client\"},operation)  "
    }
   },
   {
    "name": "pool",
    "query": {
     "query": "label_values(jvm_memory_pool_max_bytes{job=~\"$job\"},pool)  "
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System resources overview",
   "type": "bargauge",
   "description": "System resources usage",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(host_cpu_usage_sum{job=\"$job\",instance=~\"$instance\", mode=\"combined\"}[$__interval]))\n/\nsum(rate(host_cpu_usage_count{job=\"$job\",instance=~\"$instance\", mode=\"combined\"}[$__interval]))",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "host_memory_used_bytes{job=\"$job\",instance=~\"$instance\"}\n/\nhost_memory_total_bytes{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory utilization"
    },
    {
     "expr": "(host_swap_memory_used_bytes{job=\"$job\",instance=~\"$instance\"}\n/\nhost_swap_memory_total_bytes{job=\"$job\",instance=~\"$instance\"}) OR on() vector(0)",
     "legendFormat": "SWAP utilization"
    }
   ]
  },
  {
   "title": "CPU %usr",
   "type": "stat",
   "description": "Tracks the current time the CPU is busy on user mode.",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(host_cpu_usage_sum{job=\"$job\", instance=~\"$instance\", mode=\"user\"}[$__interval]))\n/\nsum(rate(host_cpu_usage_count{job=\"$job\", instance=~\"$instance\", mode=\"user\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "CPU %system",
   "type": "stat",
   "description": "Tracks the current time the CPU is busy on system mode.",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(host_cpu_usage_sum{job=\"$job\", instance=~\"$instance\", mode=\"system\"}[$__interval]))\n/\nsum(rate(host_cpu_usage_count{job=\"$job\", instance=~\"$instance\", mode=\"system\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "CPU %wait",
   "type": "stat",
   "description": "Tracks the current time the CPU is stuck waiting for IO.\n\nIf this value is high, the disk might be the bottleneck.",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(host_cpu_usage_sum{job=\"$job\", instance=~\"$instance\", mode=\"wait\"}[$__interval]))\n/\nsum(rate(host_cpu_usage_count{job=\"$job\", instance=~\"$instance\", mode=\"wait\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "bargauge",
   "description": "Traks the usage of disk space",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(host_storage_device_data_read_bytes_total{job=\"$job\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(host_storage_device_data_write_bytes_total{job=\"$job\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Retransmits",
   "type": "bargauge",
   "description": "Tracks ratio for failed network packets",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(host_network_packets_read_failed_total{job=\"$job\", instance=~\"$instance\"})\n/\nsum(host_network_packets_read_total{job=\"$job\", instance=~\"$instance\"})",
     "legendFormat": "read"
    },
    {
     "expr": "sum(host_network_packets_write_failed_total{job=\"$job\", instance=~\"$instance\"})\n/\nsum(host_network_packets_write_total{job=\"$job\", instance=~\"$instance\"})",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Top 2 Disk usage",
   "type": "stat",
   "description": "Tracks usage of space on Disk",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(2, (sum by(mount)(host_storage_mount_space_used_bytes{job=\"$job\", instance=~\"$instance\"})\n/\nsum by(mount)(host_storage_mount_space_total_bytes{job=\"$job\", instance=~\"$instance\"})))",
     "legendFormat": "{{mount}}"
    }
   ]
  },
  {
   "title": "The last processed height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ride_height{job=\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "bargauge",
   "description": "Tracks the system load average in 1m / 5m / 15m.\n\nThey indicate the average number of tasks (processes) wanting to run in the last 1m / 5m / 15m.\n\nOn Linux systems, these numbers is approximated and include processes wanting to run on the CPUs, as well as processes blocked in uninterruptible I/O (usually disk I/O).\nThis gives a high-level idea of resource load (or demand).\n\nThe three numbers give some idea of how load is changing over time.\n\nExcellent post on the subject: http://www.brendangregg.com/blog/2017-08-08/linux-load-averages.html",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "host_load_average{job=\"$job\",instance=~\"$instance\", period=\"1m\"}",
     "legendFormat": "Avg. 1m"
    },
    {
     "expr": "host_load_average{job=\"$job\",instance=~\"$instance\", period=\"5m\"}",
     "legendFormat": "Avg. 5m"
    },
    {
     "expr": "host_load_average{job=\"$job\",instance=~\"$instance\", period=\"15m\"}",
     "legendFormat": "Avg. 15m"
    }
   ]
  },
  {
   "title": "Proc %usr",
   "type": "stat",
   "description": "Tracks the current time the CPU is busy by the process in user mode.",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_usage_sum{job=\"$job\", instance=~\"$instance\", mode=\"user\"}[$__interval]))\n/\nsum(rate(process_cpu_usage_count{job=\"$job\", instance=~\"$instance\", mode=\"user\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Proc %system",
   "type": "stat",
   "description": "Tracks the current time the CPU is busy by the process in kernel mode.",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_usage_sum{job=\"$job\", instance=~\"$instance\", mode=\"system\"}[$__interval]))\n/\nsum(rate(process_cpu_usage_count{job=\"$job\", instance=~\"$instance\", mode=\"system\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "CPU %steal",
   "type": "stat",
   "description": "Tracks the current time the CPU is stolen by some process outside the VM.\n\nIf this value is high, it could be caused either by the supervisor is very busy, by a noisy neighbor or by some limitation on the quota assigned by the virtualization service.",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(host_cpu_usage_sum{job=\"$job\", instance=~\"$instance\", mode=\"stolen\"}[$__interval]))\n/\nsum(rate(host_cpu_usage_count{job=\"$job\", instance=~\"$instance\", mode=\"stolen\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "bargauge",
   "description": "Traks network usage",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(host_network_data_read_bytes_total{job=\"$job\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(host_network_data_write_bytes_total{job=\"$job\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "# FDs",
   "type": "stat",
   "description": "Tracks the number of file descriptors in used by the process.",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_ulimit_file_descriptors_used{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total scripts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ride_script_number{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput (avg. $__interval)",
     "type": "timeseries",
     "description": "The average requests rate in the last $__interval across all selected instances stacked by status",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "rpm" } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_total{instance=~\"$instance\", http_status_code=\"2xx\"}[$__interval]))",
       "legendFormat": "2xx rpm"
      },
      {
       "expr": "sum(increase(http_server_requests_total{instance=~\"$instance\", http_status_code=\"3xx\"}[$__interval]))",
       "legendFormat": "3xx rpm"
      },
      {
       "expr": "sum(increase(http_server_requests_total{instance=~\"$instance\", http_status_code=\"4xx\"}[$__interval]))",
       "legendFormat": "4xx rpm"
      },
      {
       "expr": "sum(increase(http_server_requests_total{instance=~\"$instance\", http_status_code=\"5xx\"}[$__interval]))",
       "legendFormat": "5xx rpm"
      }
     ]
    },
    {
     "title": "Latency: only 2xx status response",
     "type": "timeseries",
     "description": "Latency of requests with 2xx status response over $__interval",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(span_processing_time_seconds_bucket{instance=~\"$instance\", span_kind=\"server\", http_status_code=~\"2.*\"}[$__interval])) by (le))",
       "legendFormat": "p99.9"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(span_processing_time_seconds_bucket{instance=~\"$instance\", span_kind=\"server\", http_status_code=~\"2.*\"}[$__interval])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(span_processing_time_seconds_bucket{instance=~\"$instance\", span_kind=\"server\", http_status_code=~\"2.*\"}[$__interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(span_processing_time_seconds_bucket{instance=~\"$instance\", span_kind=\"server\", http_status_code=~\"2.*\"}[$__interval])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Approximated Uptime: 'requests with 2xx status response' / 'requests with 2xx or 5xx status response'",
     "type": "timeseries",
     "description": "Given:\n  * Success requests: status 2xx\n  * Valid requests: status 2xx or status 5xx\n\nThe uptime could be estimated by 'success requests' / 'valid requests'.\n\nThis is just an approximation because it doesn't take in account a lot of corner cases. For a more accurate metric it should be measured from outside the app.\n",
     "gridPos": { "h": 13, "w": 16, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_total{instance=~\"$instance\", http_status_code=\"2xx\"}[$__interval]))\n /\n sum(rate(http_server_requests_total{instance=~\"$instance\", http_status_code=~\"2xx|5xx\"}[$__interval]))",
       "legendFormat": "uptime"
      }
     ]
    },
    {
     "title": "2xx | 4xx | 3xx | 5xx % (avg. $__interval)",
     "type": "timeseries",
     "description": "Relative frequency distribution of response 2xx, 3xx, 4xx and 5xx over $__interval",
     "gridPos": { "h": 13, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_total{instance=~\"$instance\", http_status_code=\"5xx\"}[$__interval]))\n/\nsum(rate(http_server_requests_total{instance=~\"$instance\"}[$__interval]))",
       "legendFormat": "Failures (5xx)"
      },
      {
       "expr": "sum(rate(http_server_requests_total{instance=~\"$instance\", http_status_code=\"4xx\"}[$__interval]))\n/\nsum(rate(http_server_requests_total{instance=~\"$instance\"}[$__interval]))",
       "legendFormat": "Client errors (4xx)"
      },
      {
       "expr": "sum(rate(http_server_requests_total{instance=~\"$instance\", http_status_code=\"3xx\"}[$__interval]))\n/\nsum(rate(http_server_requests_total{instance=~\"$instance\"}[$__interval]))",
       "legendFormat": "Redirects (3xx)"
      },
      {
       "expr": "sum(rate(http_server_requests_total{instance=~\"$instance\", http_status_code=\"2xx\"}[$__interval]))\n/\nsum(rate(http_server_requests_total{instance=~\"$instance\"}[$__interval]))",
       "legendFormat": "Success (2xx)"
      }
     ]
    },
    {
     "title": "Latency: only 3xx status response",
     "type": "timeseries",
     "description": "Latency of requests with 3xx status response over $__interval",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(span_processing_time_seconds_bucket{instance=~\"$instance\", span_kind=\"server\", http_status_code=~\"3.*\"}[$__interval])) by (le))",
       "legendFormat": "p99.9"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(span_processing_time_seconds_bucket{instance=~\"$instance\", span_kind=\"server\", http_status_code=~\"3.*\"}[$__interval])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(span_processing_time_seconds_bucket{instance=~\"$instance\", span_kind=\"server\", http_status_code=~\"3.*\"}[$__interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(span_processing_time_seconds_bucket{instance=~\"$instance\", span_kind=\"server\", http_status_code=~\"3.*\"}[$__interval])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Latency: only 4xx status response",
     "type": "timeseries",
     "description": "Latency of requests with 4xx status response over $__interval",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(span_processing_time_seconds_bucket{instance=~\"$instance\", span_kind=\"server\", http_status_code=~\"4.*\"}[$__interval])) by (le))",
       "legendFormat": "p99.9"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(span_processing_time_seconds_bucket{instance=~\"$instance\", span_kind=\"server\", http_status_code=~\"4.*\"}[$__interval])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(span_processing_time_seconds_bucket{instance=~\"$instance\", span_kind=\"server\", http_status_code=~\"4.*\"}[$__interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(span_processing_time_seconds_bucket{instance=~\"$instance\", span_kind=\"server\", http_status_code=~\"4.*\"}[$__interval])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Latency: only 5xx status response",
     "type": "timeseries",
     "description": "Latency of requests with 5xx status response over $__interval",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(span_processing_time_seconds_bucket{instance=~\"$instance\", span_kind=\"server\", http_status_code=~\"5.*\"}[$__interval])) by (le))",
       "legendFormat": "p99.9"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(span_processing_time_seconds_bucket{instance=~\"$instance\", span_kind=\"server\", http_status_code=~\"5.*\"}[$__interval])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(span_processing_time_seconds_bucket{instance=~\"$instance\", span_kind=\"server\", http_status_code=~\"5.*\"}[$__interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(span_processing_time_seconds_bucket{instance=~\"$instance\", span_kind=\"server\", http_status_code=~\"5.*\"}[$__interval])) by (le))",
       "legendFormat": "p50"
      }
     ]
    }
   ]
  },
  {
   "title": "RIDE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blockchain events processing time",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, tpe) (rate(blockchain_event_process_seconds_bucket{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])))",
       "legendFormat": "{{tpe}}, 95ᵗʰ"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le, tpe) (rate(blockchain_event_process_seconds_bucket{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])))",
       "legendFormat": "{{tpe}}, 75ᵗʰ"
      }
     ]
    },
    {
     "title": "Run script time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, has_caches) (rate(ride_script_run_seconds_bucket{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])))",
       "legendFormat": "has_caches={{has_caches}}, 95ᵗʰ"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le, has_caches) (rate(ride_script_run_seconds_bucket{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])))",
       "legendFormat": "has_caches={{has_caches}}, 75ᵗʰ"
      }
     ]
    },
    {
     "title": "Batch run script time ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ride_script_run_on_height_seconds{instance=~\"$instance\", job=\"$job\"}",
       "legendFormat": "force={{force}}"
      }
     ]
    },
    {
     "title": "Whole script caches, rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "rate(ride_script_cache_hit_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "hits"
      },
      {
       "expr": "rate(ride_script_cache_miss_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "misses"
      }
     ]
    },
    {
     "title": "Caches hits, rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "rate(cache_AccountDataStorage_values_hits_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "AccountData"
      },
      {
       "expr": "rate(cache_AccountScriptStorage_values_hits_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "AccountScript"
      },
      {
       "expr": "rate(cache_AccountBalanceStorage_values_hits_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "AccountBalance"
      },
      {
       "expr": "rate(cache_AccountLeaseBalanceStorage_values_hits_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "AccountLeaseBalance"
      },
      {
       "expr": "rate(cache_VrfStorage_hits_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Vrf"
      },
      {
       "expr": "rate(cache_AssetStorage_values_hits_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Asset"
      },
      {
       "expr": "rate(cache_AliasStorage_values_hits_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Alias"
      },
      {
       "expr": "rate(cache_TransactionStorage_values_hits_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Transaction"
      }
     ]
    },
    {
     "title": "Caches evictions, rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 24 },
     "targets": [
      {
       "expr": "rate(cache_AccountDataStorage_values_evictions_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "AccountData"
      },
      {
       "expr": "rate(cache_AccountScriptStorage_values_evictions_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "AccountScript"
      },
      {
       "expr": "rate(cache_AccountBalanceStorage_values_evictions_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "AccountBalance"
      },
      {
       "expr": "rate(cache_AccountLeaseBalanceStorage_values_evictions_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "AccountLeaseBalance"
      },
      {
       "expr": "rate(cache_VrfStorage_evictions_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Vrf"
      },
      {
       "expr": "rate(cache_AssetStorage_values_evictions_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Asset"
      },
      {
       "expr": "rate(cache_AliasStorage_values_evictions_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Alias"
      },
      {
       "expr": "rate(cache_TransactionStorage_values_evictions_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Transaction"
      }
     ]
    },
    {
     "title": "Caches misses, rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 24 },
     "targets": [
      {
       "expr": "rate(cache_AccountDataStorage_values_misses_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "AccountData"
      },
      {
       "expr": "rate(cache_AccountScriptStorage_values_misses_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "AccountScript"
      },
      {
       "expr": "rate(cache_AccountBalanceStorage_values_misses_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "AccountBalance"
      },
      {
       "expr": "rate(cache_AccountLeaseBalanceStorage_values_misses_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "AccountLeaseBalance"
      },
      {
       "expr": "rate(cache_VrfStorage_misses_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Vrf"
      },
      {
       "expr": "rate(cache_AssetStorage_values_misses_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Asset"
      },
      {
       "expr": "rate(cache_AliasStorage_values_misses_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Alias"
      },
      {
       "expr": "rate(cache_TransactionStorage_values_misses_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Transaction"
      }
     ]
    },
    {
     "title": "Time in Executor queue",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, name) (rate(executor_time_in_queue_seconds_bucket{instance=~\"$instance\", job=\"$job\", akka_system=\"\"}[$__rate_interval])))",
       "legendFormat": "{{name}} 95ᵗʰ"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le, name) (rate(executor_time_in_queue_seconds_bucket{instance=~\"$instance\", job=\"$job\", akka_system=\"\"}[$__rate_interval])))",
       "legendFormat": "{{name}} 75ᵗʰ"
      }
     ]
    },
    {
     "title": "Ride calls, rate",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "rate(ride_script_calls_total{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "gRPC calls, full time",
     "type": "timeseries",
     "gridPos": { "h": 25, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(grpc_call_seconds_sum{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{method}}, raw: {{raw}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(node_db_read_bytes_sum{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{key}}"
      }
     ]
    },
    {
     "title": "Write bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(node_db_write_bytes_sum{instance=~\"$instance\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{key}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Clients metrics | $client_operation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "client_operation",
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput of outgoing requests over $__interval",
     "type": "timeseries",
     "description": "The average outgoing requests rate in the last $__interval across all selected instances",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "rpm" } },
     "targets": [
      {
       "expr": "sum by(span_kind) (increase(span_processing_time_seconds_count{instance=~\"$instance\", job=\"$job\", error=\"false\", operation=\"$client_operation\"}[$__interval]))",
       "legendFormat": "{{operation}} with no error"
      },
      {
       "expr": "sum by(span_kind) (increase(span_processing_time_seconds_count{instance=~\"$instance\", job=\"$job\", error=\"true\", operation=\"$client_operation\"}[$__interval]))",
       "legendFormat": "{{operation}} with error"
      }
     ]
    },
    {
     "title": "Latency of outgoing requests over $__interval",
     "type": "timeseries",
     "description": "Latency of outgoing requests in the last $__interval across all selected instances",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, span_kind) (rate(span_processing_time_seconds_bucket{job=\"$job\", instance=~\"$instance\", error=\"false\", operation=\"$client_operation\"}[$__interval])))",
       "legendFormat": "p99 {{operation}} with no error"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le, span_kind) (rate(span_processing_time_seconds_bucket{job=\"$job\", instance=~\"$instance\", error=\"true\", operation=\"$client_operation\"}[$__interval])))",
       "legendFormat": "p99 {{operation}} with error"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(span_processing_time_seconds_bucket{job=\"$job\", instance=~\"$instance\", error=\"false\", operation=\"$client_operation\"}[$__interval])) by (le, span_kind))",
       "legendFormat": "p90 {{operation}} with no error"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(span_processing_time_seconds_bucket{job=\"$job\", instance=~\"$instance\", error=\"true\", operation=\"$client_operation\"}[$__interval])) by (le, span_kind))",
       "legendFormat": "p90 {{operation}} with error"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(span_processing_time_seconds_bucket{job=\"$job\", instance=~\"$instance\", error=\"false\", operation=\"$client_operation\"}[$__interval])) by (le, span_kind))",
       "legendFormat": "p50 {{operation}} with no error"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(span_processing_time_seconds_bucket{job=\"$job\", instance=~\"$instance\", error=\"true\", operation=\"$client_operation\"}[$__interval])) by (le, span_kind))",
       "legendFormat": "p50 {{operation}} with error"
      }
     ]
    }
   ]
  },
  {
   "title": "Load / Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "System load average in 1m / 5m / 15m",
     "type": "timeseries",
     "description": "Tracks the system load average in 1m / 5m / 15m.\n\nThey indicate the average number of tasks (processes) wanting to run in the last 1m / 5m / 15m.\n\nOn Linux systems, these numbers is approximated and include processes wanting to run on the CPUs, as well as processes blocked in uninterruptible I/O (usually disk I/O).\nThis gives a high-level idea of resource load (or demand).\n\nThe three numbers give some idea of how load is changing over time.\n\nExcellent post on the subject: http://www.brendangregg.com/blog/2017-08-08/linux-load-averages.html",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "host_load_average{job=\"$job\",instance=~\"$instance\", period=\"1m\"}",
       "legendFormat": "Avg 1m"
      },
      {
       "expr": "host_load_average{job=\"$job\",instance=~\"$instance\", period=\"5m\"}",
       "legendFormat": "Avg 5m"
      },
      {
       "expr": "host_load_average{job=\"$job\",instance=~\"$instance\", period=\"15m\"}",
       "legendFormat": "Avg 15m"
      }
     ]
    },
    {
     "title": "VM Hiccups (or idle jitters) in nanoseconds (p90)",
     "type": "heatmap",
     "description": "Tracks the hiccups detected in the VM (also known as idle jitters) measured in nanoseconds. The 90ht percentile is presented.\n\nFor more info: https://www.azul.com/jhiccup/",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by(le, instance) (rate(process_hiccups_seconds_bucket{instance=~\"$instance\"}[$__interval])))",
       "legendFormat": "p90"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap",
     "type": "timeseries",
     "description": "Tracks the amount of memory used by the JVM heap.",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_max_bytes{job=\"$job\", instance=~\"$instance\", region=\"heap\"}",
       "legendFormat": "max"
      },
      {
       "expr": "jvm_memory_committed_bytes{job=\"$job\", instance=~\"$instance\", region=\"heap\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_used_bytes_sum{job=\"$job\", instance=~\"$instance\", region=\"heap\"}\n/\njvm_memory_used_bytes_count{job=\"$job\", instance=~\"$instance\", region=\"heap\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Off-Heap",
     "type": "timeseries",
     "description": "Tracks the amount of memory used by the JVM outside the heap.",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_max_bytes{job=\"$job\", instance=~\"$instance\", region=\"non-heap\"}",
       "legendFormat": "max"
      },
      {
       "expr": "jvm_memory_committed_bytes{job=\"$job\", instance=~\"$instance\", region=\"non-heap\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_used_bytes_sum{job=\"$job\", instance=~\"$instance\", region=\"non-heap\"}\n/\njvm_memory_used_bytes_count{job=\"$job\", instance=~\"$instance\", region=\"non-heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_free_bytes_sum{job=\"$job\", instance=~\"$instance\", region=\"non-heap\"}\n/\njvm_memory_free_bytes_count{job=\"$job\", instance=~\"$instance\", region=\"non-heap\"}",
       "legendFormat": "free"
      }
     ]
    },
    {
     "title": "Last Max by Mempools",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_max_bytes{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Last Used by Mempools",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 20, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_used_bytes_sum{job=\"$job\", instance=~\"$instance\"}\n/\njvm_memory_pool_used_bytes_count{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Garbage Collection",
     "type": "timeseries",
     "description": "Tracks the distribution of GC events duration",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_seconds_sum{job=\"$job\", instance=~\"$instance\"}[$__interval])\n/\nrate(jvm_gc_seconds_count{job=\"$job\", instance =~\"$instance\"}[$__interval])",
       "legendFormat": "GC count: {{collector}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools | $pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "pool",
   "collapsed": true,
   "panels": [
    {
     "title": "$pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_max_bytes{job=\"$job\", instance=~\"$instance\", pool=\"$pool\"}",
       "legendFormat": "max"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{job=\"$job\", instance=~\"$instance\", pool=\"$pool\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_pool_used_bytes_sum{job=\"$job\", instance=~\"$instance\", pool=\"$pool\"}\n/\njvm_memory_pool_used_bytes_count{job=\"$job\", instance=~\"$instance\", pool=\"$pool\"}",
       "legendFormat": "used"
      }
     ]
    }
   ]
  },
  {
   "title": "Executor Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number Of Threads",
     "type": "timeseries",
     "description": "Tracks the number of threads in use.",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(executor_threads_total_count{job=\"$job\", instance=~\"$instance\"}[$__interval])\n/\nrate(executor_threads_total_sum{job=\"$job\", instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{ name }} ({{ type }})"
      }
     ]
    },
    {
     "title": "Number Of Tasks Completed",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(executor_tasks_completed_total{job=\"$job\", instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{ name }} ({{ type }})"
      }
     ]
    },
    {
     "title": "Queue Size",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(executor_queue_size_bucket{job=\"$job\", instance=~\"$instance\", le=\"+Inf\"}[$__interval])",
       "legendFormat": "{{ name }} ({{ type }})"
      }
     ]
    },
    {
     "title": "Maximum Number of Threads",
     "type": "timeseries",
     "description": "Tracks maximum number of Threads of the executors.",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "executor_threads_max{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{ name }} ({{ type }})"
      }
     ]
    },
    {
     "title": "Minimum Number of Threads",
     "type": "timeseries",
     "description": "Tracks minimum number of Threads of the executors.",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "executor_threads_min{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{ name }} ({{ type }})"
      }
     ]
    },
    {
     "title": "Executor parallelism",
     "type": "timeseries",
     "description": "Tracks executor parallelism.",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "executor_parallelism{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{ name }} ({{ type }})"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk usage",
     "type": "timeseries",
     "description": "Tracks usage of disk.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(mount)(host_storage_mount_space_used_bytes{job=\"$job\", instance=~\"$instance\"})\n/\nsum by (mount)(host_storage_mount_space_total_bytes{job=\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{mount}}"
      }
     ]
    },
    {
     "title": "Data transferred",
     "type": "timeseries",
     "description": "Tracks the amount of data transferred to disk device.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(host_storage_device_data_read_bytes_total{job=\"$job\", instance=~\"$instance\"}[$__interval])",
       "legendFormat": "read"
      },
      {
       "expr": "rate(host_storage_device_data_write_bytes_total{job=\"$job\", instance=~\"$instance\"}[$__interval]) * -1",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Disk I/O (ops/sec)",
     "type": "timeseries",
     "description": "Tracks the number of completed disk I/O operations.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(host_storage_device_ops_read_total{job=\"$job\", instance=~\"$instance\"}[$__interval])",
       "legendFormat": "read"
      },
      {
       "expr": "rate(host_storage_device_ops_write_total{job=\"$job\", instance=~\"$instance\"}[$__interval]) * -1",
       "legendFormat": "write"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read / Write bandwidth",
     "type": "timeseries",
     "description": "Tracks incoming and outgoing data through the network interfaces.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(host_network_data_read_bytes_total{job=\"$job\", instance=~\"$instance\"}[$__interval])",
       "legendFormat": "read"
      },
      {
       "expr": "rate(host_network_data_write_bytes_total{job=\"$job\", instance=~\"$instance\"}[$__interval]) * -1",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Failed Read / Write packets",
     "type": "timeseries",
     "description": "Tracks incoming and outgoing failed packets on all network interfaces.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(host_network_packets_read_failed_total{job=\"$job\", instance=~\"$instance\"}[$__interval])",
       "legendFormat": "read"
      },
      {
       "expr": "rate(host_network_packets_write_failed_total{job=\"$job\", instance=~\"$instance\"}[$__interval]) * -1",
       "legendFormat": "write"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM CPU usage",
     "type": "timeseries",
     "description": "Tracks the usage of CPU by the VM in the different typical views.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(host_cpu_usage_sum{job=\"$job\", instance=~\"$instance\", mode=\"user\"}[$__interval])\n/\nrate(host_cpu_usage_count{job=\"$job\", instance=~\"$instance\", mode=\"user\"}[$__interval])",
       "legendFormat": "User mode"
      },
      {
       "expr": "rate(host_cpu_usage_sum{job=\"$job\", instance=~\"$instance\", mode=\"system\"}[$__interval])\n/\nrate(host_cpu_usage_count{job=\"$job\", instance=~\"$instance\", mode=\"system\"}[$__interval])",
       "legendFormat": "Kernel mode"
      },
      {
       "expr": "rate(host_cpu_usage_sum{job=\"$job\", instance=~\"$instance\", mode=\"wait\"}[$__interval])\n/\nrate(host_cpu_usage_count{job=\"$job\", instance=~\"$instance\", mode=\"wait\"}[$__interval])",
       "legendFormat": "IO wait"
      },
      {
       "expr": "rate(host_cpu_usage_sum{job=\"$job\", instance=~\"$instance\", mode=\"stolen\"}[$__interval])\n/\nrate(host_cpu_usage_count{job=\"$job\", instance=~\"$instance\", mode=\"stolen\"}[$__interval])",
       "legendFormat": "Stolen"
      }
     ]
    },
    {
     "title": "Process CPU usage",
     "type": "timeseries",
     "description": "Tracks the usage of CPU by the app in the different typical views.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(process_cpu_usage_sum{job=\"$job\", instance=~\"$instance\", mode=\"user\"}[$__interval])\n/\nrate(process_cpu_usage_count{job=\"$job\", instance=~\"$instance\", mode=\"user\"}[$__interval])",
       "legendFormat": "User mode"
      },
      {
       "expr": "rate(process_cpu_usage_sum{job=\"$job\", instance=~\"$instance\", mode=\"system\"}[$__interval])\n/\nrate(process_cpu_usage_count{job=\"$job\", instance=~\"$instance\", mode=\"system\"}[$__interval])",
       "legendFormat": "Kernel mode"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host Memory",
     "type": "timeseries",
     "description": "Tracks the total memory available Vs. the amount of used memory.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "host_memory_used_bytes{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "Used Memory"
      },
      {
       "expr": "host_memory_total_bytes{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "Total Memory"
      }
     ]
    },
    {
     "title": "Swap Memory",
     "type": "timeseries",
     "description": "Tracks the total swap memory available Vs. the amount of used swap memory.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "host_swap_memory_used_bytes{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "Used Swap Memory"
      },
      {
       "expr": "host_swap_memory_total_bytes{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "Total Swap Memory"
      }
     ]
    }
   ]
  }
 ]
}