package com.wavesplatform.transaction.smart.script.estimator

import com.wavesplatform.lang.v1.estimator.ScriptEstimatorV1

class ContractScriptComplexityV1Test extends ContractScriptComplexityTest(ScriptEstimatorV1)