name: Check PR
on:
  pull_request:

concurrency:
  group: check-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-pr:
    name: Check PR
    runs-on: ubuntu-latest
    outputs:
      lang-changed: ${{ steps.filter.outputs.lang == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'sbt'
          gpg-private-key: ${{ secrets.OSSRH_GPG_KEY }}
          gpg-passphrase: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
      - uses: sbt/setup-sbt@v1
      - name: Check PR
        run: sbt -J-Xlog:gc*=debug:file=./gc.log --batch "scalafmtCheck;checkPR;completeQaseRun"
        env:
          QASE_ENABLE: true
          QASE_RUN_NAME: checkPR
          QASE_RUN_ID: 1
          QASE_PROJECT_CODE: PR
          QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
          CHECKPR_RUN_ID: ${{ github.run_id }}
      - uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3
        if: always()
        with:
          reporter: java-junit
          name: JUnit Report
          path: '**/target/test-reports/*.xml'
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: |
            lang:
              - 'lang/**'
              - 'build.sbt'
              - 'project/*'
      - uses: actions/upload-artifact@v4
        if: steps.filter.outputs.lang == 'true'
        with:
          name: file-compiler
          path: lang/jvm/target/file-compiler.jar
      - name: Save debug data
        uses: actions/upload-artifact@v4
        if: always()
        with:
          if-no-files-found: ignore
          name: debug-data
          path: |
            gc.log
            hs*.log
            core*

  compile-contracts:
    name: Compile ${{ matrix.repo }}
    runs-on: ubuntu-latest
    needs: check-pr
    if: needs.check-pr.outputs.lang-changed == 'true'
    strategy:
      matrix:
        repo:
          - waves-exchange/neutrino-contract
          - waves-exchange/contracts
          - waves-ducks-core/wavesducks-public
          - swopfi/swopfi-smart-contracts
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: actions/download-artifact@v5
        with:
          name: file-compiler
      - run: find -name "*.ride" -type f -exec java -jar file-compiler.jar {} +;

  run-integration-tests:
    name: Run integration tests
    needs: check-pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1
      - name: Run Integration Tests
        run: sbt --batch "node-it/docker;node-it/test"
        env:
          RUN_ID: ${{ github.ref_name }}-${{ github.run_number }}-${{ github.run_attempt }}
      - uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3
        if: always()
        with:
          reporter: java-junit
          name: JUnit Report
          path: 'node-it/target/test-reports/*.xml'
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: cancelled() || failure()
        with:
          if-no-files-found: ignore
          name: test-logs
          path: |
            node-it/target/logs/*/

  publish-snapshots:
    name: Publish snapshot packages
    needs: check-pr
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'publish-snapshots')
    env:
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'sbt'
          gpg-private-key: ${{ secrets.OSSRH_GPG_KEY }}
          gpg-passphrase: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
      - uses: sbt/setup-sbt@v1
      - run: sbt -Dproject.version=$(awk -F '[".]' '{print $3"."$4"."$5+1}' version.sbt)-$PR_NUMBER-SNAPSHOT --batch publish
        env:
          SONATYPE_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          PGP_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
