name: Update Dependency Graph

on:
  push:
    branches:
      - 'version-1.*.*'

jobs:
  update-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: scalacenter/sbt-dependency-submission@v3
