name: Publish snapshot JARs and dependency graph

on:
  push:
    branches:
      - 'version-1.*.*'

jobs:
  update-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'
      - uses: sbt/setup-sbt@3afe9cf056c5d139bfc46579af1192d77a2f0821 # v1.4.0
      - uses: scalacenter/sbt-dependency-submission@d84eef4c09e633bcf5f113bcad7fd5e9af1baee9 # v3.2.3
        with:
          configs-ignore: test compile-internal provided
  publish-snapshot:
    name: Publish Snapshots to Sonatype
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'
          gpg-private-key: ${{ secrets.OSSRH_GPG_KEY }}
          gpg-passphrase: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
      - uses: sbt/setup-sbt@3afe9cf056c5d139bfc46579af1192d77a2f0821 # v1.4.0
      - name: Publish snapshots
        env:
          SONATYPE_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          PGP_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
        run: |
          version=$(awk -F '[".]' '{print $3"."$4"."$5+1}' version.sbt)-SNAPSHOT
          sbt -Dproject.version=$version --batch publish
