name: Build SBT docker builder for node

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: extract-versions
        run: |
          echo "waves-version=$(cut -d\" -f2 version.sbt)" >> $GITHUB_OUTPUT
          echo "sbt-version=$(cut -d= -f2 project/build.properties)" >> $GITHUB_OUTPUT
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v3
        with:
          context: ./docker
          file: ./docker/node-sbt-builder.Dockerfile
          push: true
          pull: true
          tags: wavesplatform/node-sbt-builder:${{ steps.extract-versions.outputs.waves-version }}
          build-args: |
            WAVES_VERSION=${{ steps.extract-versions.outputs.waves-version }}
            SBT_VERSION=${{ steps.extract-versions.outputs.sbt-version }}
