name: Publish aptly repo

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  create-aptly-repo:
    runs-on: ubuntu-latest
    steps:
      - run: ./.github/workflows/create-aptly-repo.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GPG_KEY_ID: ${{ secrets.OSSRH_GPG_KEY_ID }}
          GPG_PRIVATE_KEY: ${{ secrets.OSSRH_GPG_KEY }}
          GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .aptly/public
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: create-aptly-repo
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
