# NPM registry supports only one source workflow per package: https://docs.npmjs.com/trusted-publishers#for-github-actions
name: Publish packages to NPMJS
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: Package version
        required: true
      tag:
        description: Package tag
        required: true
        default: snapshot

concurrency:
  group: "npm-packages"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: NPMJS
      url: ${{ steps.publish.outputs.url }}
    permissions:
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: proudust/gh-describe@80412be8ce0e77d8afba6b340e34790bc772aa45 # v2.2.0
        id: ghd
      - uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'
      - uses: sbt/setup-sbt@3afe9cf056c5d139bfc46579af1192d77a2f0821 # v1.4.0
      - run: sbt -Dproject.version=${{ steps.ghd.outputs.describe }} --batch ';lang-tests/test;lang-tests-js/test;repl/test;langJS/fullOptJS;replJS/fullOptJS'
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: '>=24.7.0' # Trusted publishing requires npm CLI version 11.5.1 or later.
      - if: github.event_name == 'workflow_dispatch'
        run:
          echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          echo "TAG=${{ inputs.tag }}" >> $GITHUB_ENV
      - if: github.event_name == 'release'
        run: |
          echo "VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')" >> $GITHUB_ENV
          echo "TAG=latest" >> $GITHUB_ENV
      - id: publish
        run: |
          cd lang/js
          npm version $VERSION --no-git-tag-version
          npm publish --provenance --access public --tag $TAG
          cd ../../repl/js
          npm version $VERSION --no-git-tag-version
          npm publish --provenance --access public --tag $TAG
          echo "url=https://www.npmjs.com/package/@waves/ride-lang/v/$VERSION" >> "$GITHUB_OUTPUT"
