name: Publish node and lang jars to Maven Central

on:
  release:
    types: [published]

jobs:
  publish-release:
    name: Publish jars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: sbt-version
        run: |
          sbt_version=$(cut -d\" -f2 version.sbt)
          echo "sbt_version=$sbt_version" >> "$GITHUB_OUTPUT"
      - if: ${{ format('v{0}', steps.sbt-version.outputs.sbt_version) != github.ref_name }}
        env:
          SBT_VERSION: ${{ steps.sbt-version.outputs.sbt_version }}
          RELEASE_VERSION: ${{ github.ref_name }}
        run: |
          echo "::error::Release version $RELEASE_VERSION does not match SBT version $SBT_VERSION"
          exit 1
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'sbt'
          gpg-private-key: ${{ secrets.OSSRH_GPG_KEY }}
          gpg-passphrase: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
      - name: Publish release jars
        env:
          SONATYPE_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          PGP_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
        run: |
          sbt --mem 4096 --batch ";publishSigned;sonatypeBundleRelease"
