name: Publish release draft
run-name: Publish release draft for ${{ inputs.version }} from ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      networks:
        description: 'Networks'
        required: true
        default: 'mainnet testnet stagenet'
      version:
        description: 'Version'
        required: true

jobs:
  publish-release-draft:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1
      - run: ./.github/workflows/create-release-draft.sh
        env:
          RELEASE_VERSION: ${{ inputs.version }}
          RELEASE_NETWORKS: ${{ inputs.networks }}
          RELEASE_BRANCH: ${{ github.ref_name }}
